Update pry
This fixes specs breaking because of

An error occurred while loading ./spec/benchmark/memory/report_spec.rb.
Failure/Error: require 'pry'

NameError:
  undefined method `=~' for class `Pry::Code'